[workspace]

members = [
    "core",
    "db-api",
    "db-manager",
    "runner",
    "value_generator",
    "transport",
    "server",
    "client",
]

resolver = "2"

[workspace.dependencies]
log = "0.4.17"
env_logger = "0.10.1"